# Generated by Django 4.1 on 2022-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_subscribe_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(blank=True, to='base.productphoto'),
        ),
    ]
