# Generated by Django 4.1 on 2022-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_productphoto_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(to='base.productphoto'),
        ),
    ]
